from __future__ import annotations

from typing import Protocol


class Transport(Protocol):
    def open(self) -> None: ...

    def close(self) -> None: ...

    def read(self, size: int, timeout: float | None = None) -> bytes: ...

    def write(self, data: bytes) -> int: ...

    def is_open(self) -> bool: ...
